# Generated by Django 4.2.25 on 2025-10-06 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ชื่ออุปกรณ์')),
                ('device_type', models.CharField(default='ESP32', max_length=50, verbose_name='ประเภทอุปกรณ์')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='ตำแหน่ง')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของ')),
            ],
            options={
                'verbose_name': 'อุปกรณ์',
                'verbose_name_plural': 'อุปกรณ์',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ชื่อประเภท')),
                ('unit', models.CharField(max_length=20, verbose_name='หน่วย')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
            ],
            options={
                'verbose_name': 'ประเภทเซ็นเซอร์',
                'verbose_name_plural': 'ประเภทเซ็นเซอร์',
            },
        ),
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high', 'ค่าสูงเกินไป'), ('low', 'ค่าต่ำเกินไป'), ('error', 'ข้อผิดพลาด'), ('offline', 'อุปกรณ์ออฟไลน์')], max_length=20, verbose_name='ประเภทการแจ้งเตือน')),
                ('message', models.TextField(verbose_name='ข้อความแจ้งเตือน')),
                ('threshold_value', models.FloatField(blank=True, null=True, verbose_name='ค่าขีดจำกัด')),
                ('actual_value', models.FloatField(blank=True, null=True, verbose_name='ค่าจริง')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='แก้ไขแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่แจ้งเตือน')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่แก้ไข')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.device', verbose_name='อุปกรณ์')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensortype', verbose_name='ประเภทเซ็นเซอร์')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(verbose_name='ค่า')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาที่บันทึก')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='ข้อมูลดิบ')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.device', verbose_name='อุปกรณ์')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensortype', verbose_name='ประเภทเซ็นเซอร์')),
            ],
            options={
                'verbose_name': 'ข้อมูลเซ็นเซอร์',
                'verbose_name_plural': 'ข้อมูลเซ็นเซอร์',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'sensor_type', '-timestamp'], name='sensors_sen_device__c1cfd1_idx'), models.Index(fields=['-timestamp'], name='sensors_sen_timesta_c725a2_idx')],
            },
        ),
    ]
